### ISSUE TITLE
TestFlight builds 2024.13 - 2024.21 battery reports

### ISSUE THREAD

**Issue by biblicabeebli** [onnela-lab/beiwe-ios#54]
This issue is open to anyone running Testflight builds 2024.13 - 2024.20 to report your experience of the app.

_(ignore versions 2024.9-2024.12, I made a bunch of dumb mistakes.)_ This issue will be updated or retired to reflect updated build numbers if/when they appear.

Please edit previous messages with updates instead of posting a new comment, do not remove old entries.
You do not need to include Beiwe ids or the exact Beiwe server in use.

- _Please report the Maximum Capacity health percentage visible in Settings > Battery > Battery Health & Charging prominently in your post._
- Make sure to include the iPhone model you are testing on.
- Report your experience of battery drain in a brief description.
- If you have exact numbers and want to report them, please do so.
- If you have it, please report whether there is an observable change in your data quality/quantity. (We will have historical information to review, but immediate feedback is very helpful.)

(I am working on automating recording some of this information)

2024.18 is looking really good, but:
- ~I think this _cannot go to the app store_ until https://github.com/onnela-lab/beiwe-ios/issues/45 is resolved because it would destroy limited data cellular accounts _because persistence is too good._~ ok that is finished as of build 2024.19

**Comment by biblicabeebli** [comment]
I'm running several devices.

I'm getting 14% total battery drain on an iphone 8 after 6 hours of perfect persistence - this device does not have a SIM card, so no cellular radio drain, would normally expect only a handful of % loss.  100% maximum battery life

**Comment by hydawo** [comment]
Hassan

- iPhone 13 Pro Max
- Maximum Capacity health percentage = 89%
- Persistence: FOR ALL RA'S AT ONNELA LAB we will evaluate persistence by comparing data volumes prior to v2.5 (through TestFlight) to data volumes on v2.5 TestFlight versions
- We are looking for a consistency in both data collection and sensor on/off cycles. For example, if a study is configured to collected 1 minute of GPS data every 11 minutes (1 min on, 10 min off), in v2.5 we should see the data follow this cycling pattern very closely. We should then evaluate coverage % of the day. I.E. 25% of the day we have GPS data collected.

I installed v2.5 (2024.15) last Thu, 2/29/24 evening with a nearly full battery. I did anecdotally notice significantly increased battery drain - see screenshot which shows ~75% over 7 hours and 100% over 12 hours. Note I was using my phone quite a bit during this period (heavier than during the workday). 

![IMG_9032](https://github.com/onnela-lab/beiwe-ios/assets/21285757/4b85562d-5087-42de-8b60-4d92500926bd)

Interestingly, since I installed v2.5 (2024.18) I haven't noticed anymore significant battery drain as compared to prior to v2.5. I will pull a screenshot similar to the above this evening.

**Comment by daimm2000** [comment]
Michelle

- iPhone 11
- Maximum Capacity health percentage = 78%
- Test on v2.5 (2024.20)
- It took me about 10 hours to drain battery from 100% to 6%

![Image](https://github.com/onnela-lab/beiwe-ios/assets/56803789/a94cec83-b442-4146-ae4f-394a8fd15468)

**Comment by jprince127** [comment]
- IPhone 14 Pro Max
- Maximum Capacity Health Percentage: 86%
- Test on v2.5 (2024.20)
- 17 hours to drain from 100% to 25%
- Beiwe drains ~20% on average for a full day, in the past 17 hours it has drained 16%

**Comment by MMel099** [comment]
- IPhone XR
- Maximum capacity 81%
- Testing on v2.5 (2024.20)


![Image](https://github.com/onnela-lab/beiwe-ios/assets/63422396/743786e5-e49a-4fbf-abda-059e398d2436)
![Image](https://github.com/onnela-lab/beiwe-ios/assets/63422396/920d965e-4193-44d2-bb3f-434b55a46c14)
![Image](https://github.com/onnela-lab/beiwe-ios/assets/63422396/e117ba00-700e-4dc7-a2b3-092467aad885)

**Comment by hydawo** [comment]
iPhone 13 Pro Max
Maximum Capacity health percentage = 89%

~25 hours from 96% → 20%
~31 hours from 96% → 0%



![Image](https://github.com/onnela-lab/beiwe-ios/assets/21285757/cc65266c-0aed-4b0b-827b-4646d2713034)![Image](https://github.com/onnela-lab/beiwe-ios/assets/21285757/7287f354-8c1c-43ef-a6c7-899a7b6aaa78)

**Comment by jprince127** [comment]
- IPhone 14 Pro Max
- Maximum Capacity Health Percentage: 86%
- Test on v2.5 (2024.21)
- 10 hours to drain from 100% to 18%
- Beiwe drains significantly less since the update, I've noticed

![IMG_5904](https://github.com/onnela-lab/beiwe-ios/assets/143419633/8d908e31-2d8f-4448-a010-67099ff6ab3c)

**Comment by MMel099** [comment]
iPhone XR
Battery Health: 81%
~ 18 hours (including overnight) from 100% to 20%
Test on v2.5 (2024.21)
Noticeable improvement in battery drain from previous version


![Image](https://github.com/onnela-lab/beiwe-ios/assets/63422396/9aa9aa35-d8cd-4241-b392-b58ed773f7b4)



![Image](https://github.com/onnela-lab/beiwe-ios/assets/63422396/6dd2d7c4-fd7d-40d8-b585-deae50e1e592)

**Comment by daimm2000** [comment]
iPhone 11
Battery Health: 77%
~10 Hours for battery to drain from 100% to 20%
![IMG_7052](https://github.com/onnela-lab/beiwe-ios/assets/56803789/798edf7f-7ad4-4506-8620-eff09d37e0d2)
Test on v2.5 (2024.21)
Beiwe on the background running 22 hours plus

**Comment by biblicabeebli** [comment]
Thank you everyone for your time and attention on this, 2.5.0 was a really important release.

I am closing this issue now.
